name: Upload datapacks
on:
  push:
    branches:
      - main
    paths:
      - packs/**

jobs:
  Upload-Datapacks:
    runs-on: ubuntu-24.04
    steps:
      #
      # Set up Node environment
      - name: Check out code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      #
      # Test the repo
      - name: Check formatting
        run: pnpm test

      #
      # Actually run the action
      - name: Send uploading message
        run: node scripts/sendSayMessage.js
        env:
          MESSAGE_ID: "pack_uploading"
          STEL_TOKEN: ${{secrets.STEL_TOKEN}}
          STEL_SERVER_ID: ${{secrets.STEL_SERVER_ID}}

      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@d751f7ba2b7c9b18ed91a0ff6266566f4541dfbb
        with:
          server: ${{secrets.SFTP_SERVER}}
          username: ${{secrets.SFTP_USERNAME}}
          password: ${{secrets.SFTP_PASSWORD}}
          port: 2022
          delete: true # Delete the existing folder before uploading to fully replace it
          uploads: |
            ./packs/bba-extras => ./world/datapacks/bba-extras

      - name: Send uploading message
        run: node scripts/sendSayMessage.js
        env:
          MESSAGE_ID: "reload_packs_started"
          STEL_TOKEN: ${{secrets.STEL_TOKEN}}
          STEL_SERVER_ID: ${{secrets.STEL_SERVER_ID}}

      - name: Send reload command
        run: node scripts/reloadDataPacks.js
        env:
          STEL_TOKEN: ${{secrets.STEL_TOKEN}}
          STEL_SERVER_ID: ${{secrets.STEL_SERVER_ID}}

      - name: Send uploading message
        run: node scripts/sendSayMessage.js
        env:
          MESSAGE_ID: "reload_packs_finished"
          STEL_TOKEN: ${{secrets.STEL_TOKEN}}
          STEL_SERVER_ID: ${{secrets.STEL_SERVER_ID}}
