name: Upload everything
on: [workflow_dispatch]

jobs:
  Test-All:
    name: Test all
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm test

  Upload-BBA-Extras:
    name: Upload BBA Extras datapack
    runs-on: ubuntu-24.04
    needs: [Test-All]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@d751f7ba2b7c9b18ed91a0ff6266566f4541dfbb
        with:
          server: ${{secrets.SFTP_SERVER}}
          username: ${{secrets.SFTP_USERNAME}}
          password: ${{secrets.SFTP_PASSWORD}}
          port: 2022
          uploads: |
            ./packs/bba-extras => ./world/datapacks/bba-extras
          delete: "true" # Completely replace the destination

  Upload-Dynmap:
    name: Upload Dynmap config
    runs-on: ubuntu-24.04
    needs: [Test-All]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@d751f7ba2b7c9b18ed91a0ff6266566f4541dfbb
        with:
          server: ${{secrets.SFTP_SERVER}}
          username: ${{secrets.SFTP_USERNAME}}
          password: ${{secrets.SFTP_PASSWORD}}
          port: 2022
          uploads: |
            ./dynmap => ./dynmap
          ignore: |
            README.md
