name: Upload datapacks
on:
  push:
    branches:
      - main
    paths:
      - dynmap/**

jobs:
  upload:
    runs-on: ubuntu-24.04
    steps:
      - name: Test
        uses: ./.github/actions/$test.yaml

      - name: Check out code
        uses: actions/checkout@v4

      - name: SFTP upload
        uses: ./.github/actions/$sftp-upload.yaml
        with:
          uploads: |
            ./dynmap => ./dynmap
          ignore: |
            README.md
